"""
Project Inkling - Pentest Report Generator

Generate professional penetration testing reports in markdown and HTML formats.
"""

import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from .pentest_db import PentestDB, Severity, Scope

logger = logging.getLogger(__name__)


# Markdown report template
MARKDOWN_TEMPLATE = """# Penetration Test Report

**Generated:** {{ generated_date }}
**Tool:** Kali Ink Bot - AI-Powered Pentesting Assistant

---

## Executive Summary

This report summarizes the findings from penetration testing activities conducted on {{ target_count }} target(s).

### Key Findings

| Severity | Count |
|----------|-------|
| Critical | {{ vuln_counts.critical }} |
| High | {{ vuln_counts.high }} |
| Medium | {{ vuln_counts.medium }} |
| Low | {{ vuln_counts.low }} |
| Info | {{ vuln_counts.info }} |

**Total Scans:** {{ scan_count }}
**Total Vulnerabilities:** {{ total_vulns }}

---

## Scope

### Targets

| ID | IP/Host | Hostname | Scope | Notes |
|----|---------|----------|-------|-------|
{% for target in targets %}
| {{ target.id }} | {{ target.ip }} | {{ target.hostname or '-' }} | {{ target.scope }} | {{ target.notes[:30] if target.notes else '-' }} |
{% endfor %}

---

## Findings

{% if vulns_by_severity.critical %}
### Critical Vulnerabilities

{% for vuln in vulns_by_severity.critical %}
#### {{ vuln.title }}

- **Target:** {{ vuln.target_ip }}{% if vuln.port %} (Port {{ vuln.port }}){% endif %}
- **Severity:** CRITICAL{% if vuln.cvss %} (CVSS: {{ vuln.cvss }}){% endif %}
{% if vuln.cve %}- **CVE:** {{ vuln.cve }}{% endif %}
{% if vuln.service %}- **Service:** {{ vuln.service }}{% endif %}

{{ vuln.description }}

{% if vuln.evidence %}
**Evidence:**
```
{{ vuln.evidence }}
```
{% endif %}

---
{% endfor %}
{% endif %}

{% if vulns_by_severity.high %}
### High Severity Vulnerabilities

{% for vuln in vulns_by_severity.high %}
#### {{ vuln.title }}

- **Target:** {{ vuln.target_ip }}{% if vuln.port %} (Port {{ vuln.port }}){% endif %}
- **Severity:** HIGH{% if vuln.cvss %} (CVSS: {{ vuln.cvss }}){% endif %}
{% if vuln.cve %}- **CVE:** {{ vuln.cve }}{% endif %}

{{ vuln.description }}

---
{% endfor %}
{% endif %}

{% if vulns_by_severity.medium %}
### Medium Severity Vulnerabilities

{% for vuln in vulns_by_severity.medium %}
#### {{ vuln.title }}

- **Target:** {{ vuln.target_ip }}{% if vuln.port %} (Port {{ vuln.port }}){% endif %}
- **Severity:** MEDIUM{% if vuln.cvss %} (CVSS: {{ vuln.cvss }}){% endif %}
{% if vuln.cve %}- **CVE:** {{ vuln.cve }}{% endif %}

{{ vuln.description }}

---
{% endfor %}
{% endif %}

{% if vulns_by_severity.low %}
### Low Severity Vulnerabilities

{% for vuln in vulns_by_severity.low %}
- **{{ vuln.title }}** - {{ vuln.target_ip }}{% if vuln.port %} (Port {{ vuln.port }}){% endif %}
{% endfor %}
{% endif %}

{% if vulns_by_severity.info %}
### Informational

{% for vuln in vulns_by_severity.info %}
- **{{ vuln.title }}** - {{ vuln.target_ip }}
{% endfor %}
{% endif %}

---

## Scan History

| ID | Timestamp | Type | Target | Ports | Vulns | Duration |
|----|-----------|------|--------|-------|-------|----------|
{% for scan in scans %}
| {{ scan.id }} | {{ scan.timestamp_str }} | {{ scan.scan_type }} | {{ scan.target_ip }} | {{ scan.ports_found }} | {{ scan.vulns_found }} | {{ scan.duration_str }} |
{% endfor %}

---

## Recommendations

Based on the findings, the following recommendations are made:

1. **Address Critical and High Severity Issues First** - Prioritize remediation of the {{ vuln_counts.critical + vuln_counts.high }} critical/high severity vulnerabilities.

2. **Regular Vulnerability Scanning** - Implement regular automated scanning to detect new vulnerabilities.

3. **Patch Management** - Ensure all systems are kept up-to-date with security patches.

4. **Network Segmentation** - Consider network segmentation to limit lateral movement.

5. **Security Awareness** - Conduct security awareness training for staff.

---

## Appendix

### Methodology

This assessment utilized the following tools and techniques:

- **Nmap** - Network discovery and port scanning
- **Nikto** - Web vulnerability scanning
- **DNS Enumeration** - Subdomain and DNS record discovery
- **WHOIS** - Domain registration information

### Disclaimer

This report is provided for authorized security testing purposes only. The findings and recommendations are based on the state of the systems at the time of testing. Security is an ongoing process, and new vulnerabilities may be discovered after this assessment.

---

*Generated by Kali Ink Bot*
"""

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Penetration Test Report</title>
    <style>
        :root {
            --bg: #1a1a2e;
            --card-bg: #16213e;
            --text: #eee;
            --muted: #888;
            --accent: #0f3460;
            --critical: #dc3545;
            --high: #fd7e14;
            --medium: #ffc107;
            --low: #17a2b8;
            --info: #6c757d;
        }
        * { box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            background: var(--bg);
            color: var(--text);
            margin: 0;
            padding: 20px;
            line-height: 1.6;
        }
        .container { max-width: 1200px; margin: 0 auto; }
        h1, h2, h3 { margin-top: 2em; color: var(--text); }
        h1 { border-bottom: 2px solid var(--accent); padding-bottom: 10px; }
        .summary-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 15px;
            margin: 20px 0;
        }
        .stat-card {
            background: var(--card-bg);
            padding: 20px;
            border-radius: 8px;
            text-align: center;
        }
        .stat-card .value {
            font-size: 2em;
            font-weight: bold;
        }
        .stat-card.critical .value { color: var(--critical); }
        .stat-card.high .value { color: var(--high); }
        .stat-card.medium .value { color: var(--medium); }
        .stat-card.low .value { color: var(--low); }
        .stat-card.info .value { color: var(--info); }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            background: var(--card-bg);
            border-radius: 8px;
            overflow: hidden;
        }
        th, td {
            padding: 12px 15px;
            text-align: left;
            border-bottom: 1px solid var(--accent);
        }
        th { background: var(--accent); }
        tr:hover { background: rgba(255,255,255,0.05); }
        .vuln-card {
            background: var(--card-bg);
            border-radius: 8px;
            padding: 20px;
            margin: 15px 0;
            border-left: 4px solid var(--info);
        }
        .vuln-card.critical { border-left-color: var(--critical); }
        .vuln-card.high { border-left-color: var(--high); }
        .vuln-card.medium { border-left-color: var(--medium); }
        .vuln-card.low { border-left-color: var(--low); }
        .vuln-card h4 { margin: 0 0 10px 0; }
        .vuln-meta { color: var(--muted); font-size: 0.9em; }
        .badge {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 4px;
            font-size: 0.8em;
            font-weight: bold;
        }
        .badge.critical { background: var(--critical); }
        .badge.high { background: var(--high); color: #000; }
        .badge.medium { background: var(--medium); color: #000; }
        .badge.low { background: var(--low); }
        .badge.info { background: var(--info); }
        pre {
            background: #0d1117;
            padding: 15px;
            border-radius: 4px;
            overflow-x: auto;
        }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid var(--accent);
            color: var(--muted);
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Penetration Test Report</h1>
        <p><strong>Generated:</strong> {{ generated_date }}</p>
        <p><strong>Tool:</strong> Kali Ink Bot - AI-Powered Pentesting Assistant</p>

        <h2>Executive Summary</h2>
        <div class="summary-grid">
            <div class="stat-card critical">
                <div class="value">{{ vuln_counts.critical }}</div>
                <div>Critical</div>
            </div>
            <div class="stat-card high">
                <div class="value">{{ vuln_counts.high }}</div>
                <div>High</div>
            </div>
            <div class="stat-card medium">
                <div class="value">{{ vuln_counts.medium }}</div>
                <div>Medium</div>
            </div>
            <div class="stat-card low">
                <div class="value">{{ vuln_counts.low }}</div>
                <div>Low</div>
            </div>
            <div class="stat-card info">
                <div class="value">{{ vuln_counts.info }}</div>
                <div>Info</div>
            </div>
        </div>

        <p><strong>Total Targets:</strong> {{ target_count }} | <strong>Total Scans:</strong> {{ scan_count }} | <strong>Total Vulnerabilities:</strong> {{ total_vulns }}</p>

        <h2>Scope</h2>
        <table>
            <thead>
                <tr><th>ID</th><th>IP/Host</th><th>Hostname</th><th>Scope</th><th>Notes</th></tr>
            </thead>
            <tbody>
                {% for target in targets %}
                <tr>
                    <td>{{ target.id }}</td>
                    <td>{{ target.ip }}</td>
                    <td>{{ target.hostname or '-' }}</td>
                    <td>{{ target.scope }}</td>
                    <td>{{ target.notes[:50] if target.notes else '-' }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <h2>Findings</h2>

        {% for severity in ['critical', 'high', 'medium', 'low', 'info'] %}
        {% if vulns_by_severity[severity] %}
        <h3>{{ severity|title }} ({{ vulns_by_severity[severity]|length }})</h3>
        {% for vuln in vulns_by_severity[severity] %}
        <div class="vuln-card {{ severity }}">
            <h4>{{ vuln.title }}</h4>
            <div class="vuln-meta">
                <span class="badge {{ severity }}">{{ severity|upper }}</span>
                Target: {{ vuln.target_ip }}
                {% if vuln.port %}| Port: {{ vuln.port }}{% endif %}
                {% if vuln.cvss %}| CVSS: {{ vuln.cvss }}{% endif %}
                {% if vuln.cve %}| {{ vuln.cve }}{% endif %}
            </div>
            {% if vuln.description %}
            <p>{{ vuln.description }}</p>
            {% endif %}
            {% if vuln.evidence %}
            <pre>{{ vuln.evidence }}</pre>
            {% endif %}
        </div>
        {% endfor %}
        {% endif %}
        {% endfor %}

        <h2>Scan History</h2>
        <table>
            <thead>
                <tr><th>ID</th><th>Timestamp</th><th>Type</th><th>Target</th><th>Ports</th><th>Vulns</th><th>Duration</th></tr>
            </thead>
            <tbody>
                {% for scan in scans %}
                <tr>
                    <td>{{ scan.id }}</td>
                    <td>{{ scan.timestamp_str }}</td>
                    <td>{{ scan.scan_type }}</td>
                    <td>{{ scan.target_ip }}</td>
                    <td>{{ scan.ports_found }}</td>
                    <td>{{ scan.vulns_found }}</td>
                    <td>{{ scan.duration_str }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <h2>Recommendations</h2>
        <ol>
            <li><strong>Address Critical and High Severity Issues First</strong> - Prioritize remediation of the {{ vuln_counts.critical + vuln_counts.high }} critical/high severity vulnerabilities.</li>
            <li><strong>Regular Vulnerability Scanning</strong> - Implement regular automated scanning.</li>
            <li><strong>Patch Management</strong> - Keep all systems up-to-date with security patches.</li>
            <li><strong>Network Segmentation</strong> - Limit lateral movement potential.</li>
            <li><strong>Security Awareness</strong> - Conduct security training for staff.</li>
        </ol>

        <div class="footer">
            <p>Generated by Kali Ink Bot - AI-Powered Pentesting Assistant</p>
        </div>
    </div>
</body>
</html>
"""


class ReportGenerator:
    """
    Generate penetration testing reports.

    Supports markdown and HTML output formats.
    """

    def __init__(self, db: PentestDB):
        """Initialize report generator."""
        self.db = db

    def generate(
        self,
        target_ids: List[int],
        format: str = "markdown",
    ) -> str:
        """
        Generate a pentest report.

        Args:
            target_ids: List of target IDs to include
            format: Output format ("markdown" or "html")

        Returns:
            Report content as string
        """
        # Gather data
        targets = []
        for tid in target_ids:
            target = self.db.get_target(tid)
            if target:
                targets.append({
                    "id": target.id,
                    "ip": target.ip,
                    "hostname": target.hostname,
                    "scope": target.scope.value,
                    "notes": target.notes,
                })

        # Get all scans for these targets
        scans = []
        for tid in target_ids:
            target_scans = self.db.get_scans(target_id=tid, limit=50)
            target = self.db.get_target(tid)
            for s in target_scans:
                scans.append({
                    "id": s.id,
                    "target_ip": target.ip if target else str(tid),
                    "scan_type": s.scan_type.value.upper(),
                    "ports_found": s.ports_found,
                    "vulns_found": s.vulns_found,
                    "timestamp_str": datetime.fromtimestamp(s.timestamp).strftime("%Y-%m-%d %H:%M"),
                    "duration_str": f"{s.duration_sec:.1f}s" if s.duration_sec else "-",
                })

        # Get all vulnerabilities grouped by severity
        vulns_by_severity: Dict[str, List[Dict]] = {
            "critical": [],
            "high": [],
            "medium": [],
            "low": [],
            "info": [],
        }

        for tid in target_ids:
            target = self.db.get_target(tid)
            target_vulns = self.db.get_vulns(target_id=tid, limit=100)
            for v in target_vulns:
                vulns_by_severity[v.severity.value].append({
                    "id": v.id,
                    "target_ip": target.ip if target else str(tid),
                    "title": v.title,
                    "description": v.description,
                    "severity": v.severity.value,
                    "cvss": v.cvss,
                    "cve": v.cve,
                    "port": v.port,
                    "service": v.service,
                    "evidence": v.evidence,
                })

        # Count vulnerabilities
        vuln_counts = {
            "critical": len(vulns_by_severity["critical"]),
            "high": len(vulns_by_severity["high"]),
            "medium": len(vulns_by_severity["medium"]),
            "low": len(vulns_by_severity["low"]),
            "info": len(vulns_by_severity["info"]),
        }
        total_vulns = sum(vuln_counts.values())

        # Build template context
        context = {
            "generated_date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "target_count": len(targets),
            "scan_count": len(scans),
            "total_vulns": total_vulns,
            "vuln_counts": vuln_counts,
            "targets": targets,
            "scans": sorted(scans, key=lambda x: x["id"], reverse=True),
            "vulns_by_severity": vulns_by_severity,
        }

        # Render template
        template_str = HTML_TEMPLATE if format == "html" else MARKDOWN_TEMPLATE

        try:
            from jinja2 import Template
            template = Template(template_str)
            return template.render(**context)
        except ImportError:
            # Fallback to simple string replacement if Jinja2 not available
            return self._simple_render(template_str, context)

    def _simple_render(self, template: str, context: Dict[str, Any]) -> str:
        """Simple template rendering without Jinja2."""
        result = template

        # Replace simple variables
        for key, value in context.items():
            if isinstance(value, (str, int, float)):
                result = result.replace(f"{{{{ {key} }}}}", str(value))

        # Handle nested dict access
        if "vuln_counts" in context:
            for k, v in context["vuln_counts"].items():
                result = result.replace(f"{{{{ vuln_counts.{k} }}}}", str(v))

        return result
